apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-petclinic
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/tiffanyfay/tdc-examples
      ref: origin/main
      subPath: carvel/ex-minimal
  template:
  - ytt: {}
  deploy:
  - kapp: {}